---
abstract: 'Generate POD documentation for subs'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200003, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Spec-Pod
requires:
  Clone::Any: 0
  Data::Dump::Partial: 0
  JSON: 0
  List::MoreUtils: 0
  Log::Any: 0
  Sub::Spec::CmdLine: 0
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Sub-Spec-Pod/
  repository: http://github.com/sharyanto/perl-Sub-Spec-Pod
version: 0.09
